# Generated by Django 4.1.1 on 2022-12-19 12:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
